services:
    postgres:
        container_name: postgres-sql-bsn
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /var/lib/postgresql/data
            POSTGRES_DB: book_social_network
        volumes:
            - postgres:/data/postgres
        networks:
            - spring-boot-network
        restart: unless-stopped
    mail-dev:
        container_name: maildev-bsn
        image: maildev/maildev
        ports:
            - "1080:1080"
            - "1025:1025"
networks:
    spring-boot-network:
        driver: bridge

volumes:
    postgres:
        driver: local