/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookRequest {
  id?: number;
  authorName: string;
  isbn: string;
  synopsis: string;
  title: string;
  sharable?: boolean;
}
